spring.datasource.url=jdbc:sqlite:bcruz-dev.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.sql.init.platform=sqlite
spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

stripe.secret-key=test_key
stripe.publishable-key=test_publishable
stripe.webhook-secret=test_webhook

app.cors.allowed-origins=http://localhost:5173