spring.datasource.url=jdbc:sqlite:test-database.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.sql.init.platform=sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

stripe.secret-key=test_key
stripe.publishable-key=test_publishable
stripe.webhook-secret=test_webhook

app.cors.allowed-origins=http://localhost:5173