stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.publishable.key=${STRIPE_PUBLISHABLE_KEY}
spring.application.name=bcruz

# JDBC URL for SQLite
spring.datasource.url=jdbc:sqlite:bcruzdatabase.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA / Hibernate settings
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update