spring.datasource.url=jdbc:sqlite:test-database.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.sql.init.platform=sqlite
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true