stripe.secretKey=${STRIPE_SECRET_KEY}
stripe.publishableKey=${STRIPE_PUBLISHABLE_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
spring.application.name=bcruz

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true