spring.application.name=bcruz

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
logging.level.org.hibernate.SQL=warn
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never