name: CI & Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SPRING_PROFILES_ACTIVE: test
      CI: true

      DB_URL: jdbc:sqlite:test.db

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------- Node (frontend) ----------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install frontend dependencies
        working-directory: ecommerce-front
        run: npm ci

      - name: Build frontend
        working-directory: ecommerce-front
        env:
          VITE_STRIPE_PUBLIC_KEY: ${{ secrets.VITE_STRIPE_PUBLIC_KEY }}
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: npm run build

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: ecommerce-front/dist

      # ---------- Java (backend) ----------
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Make mvnw executable
        working-directory: ecommerce-backend
        run: chmod +x mvnw

      - name: Build backend
        working-directory: ecommerce-backend
        run: ./mvnw clean test

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Render
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"

      - name: Install Netlify CLI
        run: npm install -g netlify-cli@latest

      - uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: dist
      
      - name: Debug Netlify access
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          netlify status
          netlify sites:list

      - name: Verify Netlify sites
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          netlify sites:list

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_PROJECT_ID: ${{ secrets.NETLIFY_PROJECT_ID }}
        run: |
          netlify deploy \
            --site "$NETLIFY_PROJECT_ID" \
            --dir=dist \
            --prod \
            --no-build \
            --message "Deploy from GitHub Actions ${{ github.sha }}" \
            --json > deploy.json

      - name: Save deploy URL
        run: cat deploy.json | jq -r .deploy_url > deploy-url.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-url
          path: deploy-url.txt